{-# OPTIONS --sized-types --without-K #-}

module Everything where

import Relation.Unary.Bunched.Checked
import Relation.Unary.Bunched.Properties
import Relation.Unary.Bunched.Synth
import Relation.Unary.Checked
import Relation.Unary.Bunched
import Relation.Unary.Extra
import Relation.Binary.Setoid
import Generic.Linear.Algebra
import Generic.Linear.Variable
import Generic.Linear.Environment.Properties
import Generic.Linear.Environment.Categorical
import Generic.Linear.Example.Mono
import Generic.Linear.Example.ZeroOneMany.Affine
import Generic.Linear.Example.ZeroOneMany
import Generic.Linear.Renaming.Properties
import Generic.Linear.Renaming.Monoidal
import Generic.Linear.Environment
import Generic.Linear.Operations
import Generic.Linear.Everything
import Data.Wrap.Top
import Data.LTree
import Data.Bool.Extra
import Data.LTree.Vector
import Data.LTree.Automation
import Data.LTree.Vector.Properties
import Data.LTree.Matrix
import Data.LTree.Matrix.Properties
import Data.Hand
import Algebra.Relational
import Algebra.Skew.Definitions
import Algebra.Skew.Definitions.Left
import Algebra.Skew.Definitions.Both
import Algebra.Skew.Definitions.Right
import Algebra.Skew.Construct.Vector
import Algebra.Skew.Relation
import Algebra.Relational.Construct.Vector
import Algebra.Relational.Relation
import Algebra.Po
import Algebra.Po.Construct.Vector
import Algebra.Po.Construct.Nat
import Algebra.Po.Relation
import Algebra.Skew
import Algebra.PoToRel
import Function.Extra

import Generic.Linear.Syntax
import Generic.Linear.Example.PaperExamples
import Generic.Linear.Example.MuMuTilde.Term
import Generic.Linear.Example.WRel
import Generic.Linear.Example.UsageCheck
import Generic.Linear.Example.PaperExamples.HeavyI
import Generic.Linear.Example.WRel.Monotonicity
import Generic.Linear.Example.MuMuTilde
import Generic.Linear.Semantics
import Generic.Linear.Semantics.Syntactic
import Generic.Linear.Renaming
import Generic.Linear.Syntax.Term
import Generic.Linear.Syntax.Interpretation.Map
import Generic.Linear.Syntax.Interpretation
